### ISSUE TITLE
Python API: mgxs.FissionXS.print_xs()

### ISSUE THREAD

**Issue by tjlaboss** [mit-crpg/openmc#795]
The method print_xs() of class openmc.mgxs.FissionXS fails with the following error message:

```language=python
Traceback (most recent call last):
  File "/home/travis/Research/spam-xs/fix_mesh.py", line 78, in <module>
    fission_mgxs.print_xs()
  File "/home/travis/.anaconda3/lib/python3.5/site-packages/openmc-0.8.0-py3.5-linux-x86_64.egg/openmc/mgxs/mgxs.py", line 1343, in print_xs
    xs_type=xs_type, value='mean')
  File "/home/travis/.anaconda3/lib/python3.5/site-packages/openmc-0.8.0-py3.5-linux-x86_64.egg/openmc/mgxs/mgxs.py", line 830, in get_xs
    filter_bins=filter_bins, value=value)
  File "/home/travis/.anaconda3/lib/python3.5/site-packages/openmc-0.8.0-py3.5-linux-x86_64.egg/openmc/tallies.py", line 1493, in get_values
    filter_indices = self.get_filter_indices(filters, filter_bins)
  File "/home/travis/.anaconda3/lib/python3.5/site-packages/openmc-0.8.0-py3.5-linux-x86_64.egg/openmc/tallies.py", line 1343, in get_filter_indices
    filter_index = self.get_filter_index(type(self_filter), bin)
  File "/home/travis/.anaconda3/lib/python3.5/site-packages/openmc-0.8.0-py3.5-linux-x86_64.egg/openmc/tallies.py", line 1179, in get_filter_index
    filter_index = filter_found.get_bin_index(filter_bin)
  File "/home/travis/.anaconda3/lib/python3.5/site-packages/openmc-0.8.0-py3.5-linux-x86_64.egg/openmc/filter.py", line 942, in get_bin_index
    deltas = np.abs(self.bins - filter_bin[1]) / filter_bin[1]
IndexError: tuple index out of range
```

**Comment by tjlaboss** [comment]
This can be reproduced by cell [31] of http://openmc.readthedocs.io/en/latest/pythonapi/examples/mgxs-part-iii.html

**Comment by wbinventor** [comment]
@tjlaboss I don't see this error with the latest version of the "develop" branch. Which Git commit are you using? Are you able to update your version?

**Comment by tjlaboss** [comment]
@wbinventor 

**Git SHA1 | 5afd4c369fab20b8f296dc339e1f39a62171de15**

I'll pull the latest develop ASAP and see if this resolves it

**Comment by wbinventor** [comment]
Ok great. I'm not sure why `MGXS.print_xs(...)` would fail for that commit, but hopefully you won't see this issue with the latest version of the code.

**Comment by tjlaboss** [comment]
Yep, looks like it's been fixed since the build i was using!
